name: memycameraandYou
favicon: null
layout_spectrum: 0.27081
typography_spectrum: 0.46625
title: 'me, my camera and You'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a0a0a0'
    - '#00a000'
    - '#b5b5b5'
    - '#84d184'
  brandStrength: 0.75
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
