name: memycameraandYou
favicon: null
layout_spectrum: 0.8010886730626225
typography_spectrum: 0.6282927768770605
title: 'me, my camera and You'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.12031807308085263
  lightness: 0.46225145156495273
  saturation: 0.3962013144046068
  rhythmicContrast: 0.5132559733465314
purpose: []
